package task;

public enum FeedbackQuality {
    OFTEN_EXCEEDS_EXPECTATION,
    SOMETIMES_EXCEEDS_EXPECTATION,
    MEETS_EXPECTATION,
    SOMETIMES_FAILS_TO_MEET_EXPECTATION,
    OFTEN_FAILS_TO_MEET_EXPECTATION
}
